### ISSUE TITLE
layout not found 

### ISSUE THREAD

**Issue by fccoelho** [jeffknupp/sandman2#10]
I am getting this error on sandman2ctl with postgresql

jinja2.exceptions.TemplateNotFound: layout.html

**Comment by DanielJoyce** [comment]
Same issue here. Installed via pip
 
pip install sandman2 doesn't seem to include templates, only the code/modules

**Comment by DanielJoyce** [comment]
layout.css is missing as well, its not in the repo after I cloned it.

**Comment by jeffknupp** [comment]
The file is not required, removing it from the template now.

**Comment by m3talstorm** [comment]
sudo pip install git+https://github.com/jeffknupp/sandman2.git

Worked for me

**Comment by dbaty** [comment]
I can reproduce the TemplateNotFound with the latest version of `sandman` (1.0.4):

    [2016-10-11 14:30:47,654] ERROR in app: Exception on /admin/ [GET]
    Traceback (most recent call last):
      File "/path/to/env/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
        response = self.full_dispatch_request()
      File "/path/to/env/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/path/to/env/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/path/to/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/path/to/env/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
        rv = self.dispatch_request()
      File "/path/to/env/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/path/to/env/lib/python3.5/site-packages/flask_admin/base.py", line 69, in inner
        return self._run_view(f, *args, **kwargs)
      File "/path/to/env/lib/python3.5/site-packages/flask_admin/base.py", line 368, in _run_view
        return fn(self, *args, **kwargs)
      File "/path/to/env/lib/python3.5/site-packages/flask_admin/base.py", line 452, in index
        return self.render(self._template)
      File "/path/to/env/lib/python3.5/site-packages/flask_admin/base.py", line 308, in render
        return render_template(template, **kwargs)
      File "/path/to/env/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
        context, ctx.app)
      File "/path/to/env/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
        rv = template.render(context)
      File "/path/to/env/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/path/to/env/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/path/to/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/path/to/env/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/index.html", line 1, in top-level template code
        {% extends 'admin/master.html' %}
      File "/path/to/env/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
        {% extends admin_base_template %}
      File "/path/to/env/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
        return self._get_source_fast(environment, template)
      File "/path/to/env/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: layout.html

Indeed there are no `templates/` directory installed by `pip install sandman2`:

    $ ls -l /path/to/env/lib/python3.5/site-packages/sandman2/
    total 52
    -rw-r--r-- 1 damien damien  459 12 sept. 20:29 admin.py
    -rw-r--r-- 1 damien damien 6718 12 sept. 20:29 app.py
    -rw-r--r-- 1 damien damien 2745 12 sept. 20:29 decorators.py
    -rw-r--r-- 1 damien damien 2689 12 sept. 20:29 exception.py
    -rw-r--r-- 1 damien damien   83 12 sept. 20:29 __init__.py
    -rw-r--r-- 1 damien damien 4512 12 sept. 20:29 model.py
    drwxr-xr-x 2 damien damien 4096 11 oct.  14:25 __pycache__
    drwxr-xr-x 3 damien damien 4096 11 oct.  14:25 scripts
    -rw-r--r-- 1 damien damien 9727 20 sept. 21:33 service.py

But files in `templates/layout.html` are necessary for the admin.

Could it be a packaging issue?

**Comment by skunkwerk** [comment]
+1 same issue here with fresh 'pip install sandman2'
