### ISSUE TITLE
AttributeError: module 'sqlalchemy.util' has no attribute 'deprecated_params'

### ISSUE THREAD

**Issue by ibstelix** [jeffknupp/sandman2#100]
Hi,
this is a new installation (previously i had no problem).
I ran sandman2ctl mysql+pymysql://user:pwd@localhost/foo
and got :
`
Traceback (most recent call last):
  File "$HOME/.local/bin/sandman2ctl", line 7, in <module>
    from sandman2.scripts.sandman2ctl import main
  File "$HOME/.local/lib/python3.6/site-packages/sandman2/__init__.py", line 2, in <module>
    from sandman2.app import get_app, db, AutomapModel
  File "$HOME/.local/lib/python3.6/site-packages/sandman2/app.py", line 5, in <module>
    from sqlalchemy.sql import sqltypes
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/__init__.py", line 9, in <module>
    from .sql import (
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/sql/__init__.py", line 101, in <module>
    __go(locals())
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/sql/__init__.py", line 99, in __go
    from . import naming
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/sql/naming.py", line 15, in <module>
    from .. import event, events
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/events.py", line 11, in <module>
    from .pool import Pool
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/pool/__init__.py", line 20, in <module>
    from .base import _ConnectionFairy  # noqa
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 57, in <module>
    class Pool(log.Identified):
  File "$HOME/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 63, in Pool
    @util.deprecated_params(
AttributeError: module 'sqlalchemy.util' has no attribute 'deprecated_params'
`
Version issue ?

**Comment by jeffknupp** [comment]
Looking at this now. Thanks for reporting.

**Comment by jeffknupp** [comment]
This works for me with the most recent version of `sandman2` (1.2.0) and `pymysql` (0.9.3)

```
$ sandman2ctl mysql+pymysql://root@localhost/foo                             ✭ ◼
 * Serving Flask app "sandman2" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```
Can you check which versions of each you're using?

**Comment by ibstelix** [comment]
Sorry for this sooo late reply, it is working when i retested, so maybe it was related to my environment.\
Best regards,
