### ISSUE TITLE
sqlalchemy.exc.ArgumentError

### ISSUE THREAD

**Issue by rustanacexd** [jeffknupp/sandman2#116]
I am getting an error from the get go, thoughts? This is for mssql 2012

```
sandman2ctl mssql+pymssql://USERNAMEHERE:PASSWORDHERE@HOSTHERE/DBNAMEHERE
Traceback (most recent call last):
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/bin/sandman2ctl", line 10, in <module>
    sys.exit(main())
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sandman2/scripts/sandman2ctl.py", line 51, in main
    app = get_app(args.URI, read_only=args.read_only, schema=args.schema)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sandman2/app.py", line 60, in get_app
    _reflect_all(exclude_tables, admin, read_only, schema=schema)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sandman2/app.py", line 139, in _reflect_all
    register_model(cls, admin)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sandman2/app.py", line 156, in register_model
    cols = list(cls().__table__.primary_key.columns)
  File "<string>", line 2, in __init__
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 373, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 199, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 297, in __call__
    fn(*args, **kw)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3341, in _event_on_first_init
    configure_mappers()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3229, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1864, in do_init
    self._generate_backref()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2121, in _generate_backref
    mapper._configure_property(backref_key, relationship)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1840, in _configure_property
    prop.init()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1864, in do_init
    self._generate_backref()
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2124, in _generate_backref
    self._add_reverse_property(self.back_populates)
  File "/Users/rustanacecorpuz/.virtualenvs/sandman2/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1815, in _add_reverse_property
    % (other, self, self.direction)
sqlalchemy.exc.ArgumentError: incident_request_type.incident_request_type and back-reference incident_request_type.incident_request_type_collection are both of the same direction symbol('ONETOMANY').  Did you mean to set remote_side on the many-to-one side ?
```

**Comment by jeffknupp** [comment]
Is it possible to post a dump of the schema for the tables in question?
