### ISSUE TITLE
running sandman2 on virtualenv on ubuntu

### ISSUE THREAD

**Issue by waleedsaud** [jeffknupp/sandman2#16]
when I run on sqlite db file I get this error fro admin page:

Traceback (most recent call last):
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask_admin/base.py", line 443, in index
    return self.render(self._template)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask_admin/base.py", line 299, in render
    return render_template(template, **kwargs)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/index.html", line 1, in top-level template code
    {% extends 'admin/master.html' %}
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/vagrant/sandman2/venv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: layout.html

**Comment by cfljam** [comment]
same for me on pg

**Comment by jeffknupp** [comment]
Fixed in version 0.0.7
